In [2]:
import numpy as np

In [ ]:
#1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
a = np.array([0,1,2,3,4,5])

In [22]:
b = np.array([0,1,2,3,4,6])

In [15]:
a.all()

False

In [16]:
#2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [17]:
a.any()

True

In [ ]:
#3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [23]:
np.allclose(a, b)

False

In [24]:
#4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [37]:
np.zeros(10) , np.ones(10) , np.ones(10)*5

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [38]:
#5. Write a NumPy program to create an array of the integers from 30 to70.

In [40]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [41]:
#6. Write a NumPy program to create a 3x3 identity matrix

In [43]:
x = np.diag([1,1,1])
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
#7. Write a NumPy program to generate a random number between 0 and 1

In [49]:
np.random.uniform(0,1)

0.10438541685254721

In [47]:
#8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [51]:
np.random.randint(1,100,15)

array([69, 41, 31,  2,  3, 25, 75, 86, 23,  2, 98, 23, 40, 92, 21])

In [52]:
#9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [53]:
v = np.arange(15,56)

In [55]:
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [56]:
#10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [57]:
v1 = np.random.randint(0,10,5)

In [60]:
v1

array([7, 3, 2, 9, 8])

In [61]:
#11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [128]:
x = np.zeros((10,10)).astype(int)

In [129]:
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [130]:
x[:,0 ] = 1
x[0,:] = 1
x[-1,:] = 1
x[:, -1] = 1

In [131]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [72]:
#12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [73]:
a = np.diag([1,2,3,4,5])

In [74]:
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [75]:
#13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [199]:
y = np.zeros((4,4)).astype(int)
y

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [200]:
y[::2, 1::2] = 1
y[1::2, ::2] = 1

In [201]:
y

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [202]:
#14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [217]:
f = np.arange(1,7)
h = np.arange(7,14)

In [220]:
n = np.savez_compressed("fh.npz", x=f, z=h)

In [223]:
n = np.load("fh.npz")
n["x"]

array([1, 2, 3, 4, 5, 6])

In [224]:
#15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select

In [236]:
np.random.seed(1)
np.random.randint(1,100,40)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29, 30, 15, 51, 69, 88, 88, 95, 97, 87, 14, 10,  8, 64, 62,
       23, 58,  2,  1, 61, 82])

In [237]:
#16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number

In [238]:
k = np.arange(1,11)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
k[k>4]

array([ 5,  6,  7,  8,  9, 10])

In [240]:
k[k<8]

array([1, 2, 3, 4, 5, 6, 7])